# Generated by Django 2.2.4 on 2020-03-05 15:20

from django.db import migrations, models
import django.db.models.deletion
import otree.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('otree', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_subsession', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('distribution_rule', otree.db.models.StringField(max_length=10000, null=True)),
                ('threshold', otree.db.models.CurrencyField(null=True)),
                ('bonus', otree.db.models.CurrencyField(null=True)),
                ('total_contribution', otree.db.models.CurrencyField(null=True)),
                ('avg_contribution', otree.db.models.CurrencyField(null=True)),
                ('avg_payoff', otree.db.models.CurrencyField(null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pggexoen_group', to='otree.Session')),
            ],
            options={
                'db_table': 'PGGexoEN_group',
            },
        ),
        migrations.CreateModel(
            name='Subsession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pggexoen_subsession', to='otree.Session')),
            ],
            options={
                'db_table': 'PGGexoEN_subsession',
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_group', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('_payoff', otree.db.models.CurrencyField(default=0, null=True)),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('_gbat_arrived', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, null=True)),
                ('_gbat_grouped', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, null=True)),
                ('contribution', otree.db.models.CurrencyField(null=True)),
                ('value', otree.db.models.CurrencyField(null=True)),
                ('prule', otree.db.models.PositiveIntegerField(choices=[[0, 'Equal share of the bonus'], [1, 'Equal payoff']], null=True)),
                ('payoff_r', otree.db.models.CurrencyField(null=True)),
                ('check_r', otree.db.models.FloatField(null=True)),
                ('earnings_phase1', otree.db.models.CurrencyField(null=True)),
                ('earnings_phase2', otree.db.models.CurrencyField(null=True)),
                ('earnings_phase3', otree.db.models.CurrencyField(null=True)),
                ('paid', otree.db.models.FloatField(null=True)),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='PGGexoEN.Group')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pggexoen_player', to='otree.Participant')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pggexoen_player', to='otree.Session')),
                ('subsession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PGGexoEN.Subsession')),
            ],
            options={
                'db_table': 'PGGexoEN_player',
            },
        ),
        migrations.AddField(
            model_name='group',
            name='subsession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PGGexoEN.Subsession'),
        ),
    ]
