# Generated by Django 2.2.4 on 2020-03-09 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PGGexoEN', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='earnings_phase2',
        ),
        migrations.RemoveField(
            model_name='player',
            name='earnings_phase3',
        ),
    ]
