# Generated by Django 2.2.4 on 2020-03-09 16:36

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('PGGexoEN', '0002_auto_20200309_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='paid',
            field=otree.db.models.CurrencyField(null=True),
        ),
    ]
