# Generated by Django 2.2.4 on 2020-03-10 11:44

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('PGGexoEN', '0003_auto_20200309_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='code',
            field=otree.db.models.StringField(max_length=10000, null=True, verbose_name='Your unique code'),
        ),
    ]
