# Generated by Django 2.2.4 on 2020-03-11 12:55

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('PGGexoEN', '0004_player_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='code',
        ),
        migrations.AddField(
            model_name='player',
            name='comprehension_1',
            field=otree.db.models.StringField(max_length=10000, null=True, verbose_name='Your unique code'),
        ),
    ]
