# Generated by Django 2.2.4 on 2020-03-11 16:08

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('PGGexoEN', '0006_auto_20200311_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='comprehension_2',
            field=otree.db.models.PositiveIntegerField(null=True, verbose_name='If you invested 4 tokens in the public good, how much of your income do you still have left?'),
        ),
        migrations.AddField(
            model_name='player',
            name='comprehension_3',
            field=otree.db.models.PositiveIntegerField(null=True, verbose_name='If you invested 4 tokens in the public good, how much of your income do you still have left?'),
        ),
    ]
