# Generated by Django 2.2.4 on 2020-03-18 14:38

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('PGGexoEN', '0009_auto_20200311_1745'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='comprehension_1',
        ),
        migrations.RemoveField(
            model_name='player',
            name='comprehension_2',
        ),
        migrations.RemoveField(
            model_name='player',
            name='comprehension_3',
        ),
        migrations.AddField(
            model_name='player',
            name='comprehension1',
            field=otree.db.models.PositiveIntegerField(null=True, verbose_name='If you invested 4 tokens in the public good, how much of your income do you still have left?'),
        ),
        migrations.AddField(
            model_name='player',
            name='comprehension2',
            field=otree.db.models.FloatField(null=True, verbose_name='There are 10 people in your group. Your income (endowment) is 10 tokens. The public good threshold is 25 tokens. The group bonus for achieving the threshold is 50 tokens, equally divided between the group, e.g. 5 tokens for each player. You have contributed 3,5 tokens towards the public good. The contributions of the other 9 people in your group are as follows {0; 2.5; 3; 0; 2; 2.5; 3; 3; 4}. What is your payoff for this round?'),
        ),
        migrations.AddField(
            model_name='player',
            name='comprehension3',
            field=otree.db.models.PositiveIntegerField(null=True, verbose_name='If you invested 4 tokens in the public good, how much of your income do you still have left?'),
        ),
    ]
