# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2020-03-27 09:02
from __future__ import unicode_literals

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('PGGexoEN', '0010_auto_20200318_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='comprehension1',
            field=otree.db.models.PositiveIntegerField(null=True, verbose_name='If you contributed 20 tokens to the public good, how much of your income do you still have left?'),
        ),
    ]
