# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2020-03-27 10:33
from __future__ import unicode_literals

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('PGGexoEN', '0011_auto_20200327_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='comprehension2',
            field=otree.db.models.PositiveIntegerField(null=True, verbose_name='There are 10 people in your group. Your income (endowment) is 10 tokens. The public good threshold is 25 tokens. The group bonus for achieving the threshold is 50 tokens, equally divided between the group, e.g. 5 tokens for each player. You have contributed 3,5 tokens towards the public good. The contributions of the other 9 people in your group are as follows {0; 2.5; 3; 0; 2; 2.5; 3; 3; 4}. What is your payoff for this round?'),
        ),
        migrations.AlterField(
            model_name='player',
            name='earnings_phase1',
            field=otree.db.models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='paid',
            field=otree.db.models.PositiveIntegerField(null=True),
        ),
    ]
