# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2020-03-27 12:13
from __future__ import unicode_literals

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('PGGexoEN', '0014_auto_20200327_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='explore_reasons',
            field=otree.db.models.StringField(max_length=10000, null=True, verbose_name='Please state the reasons for your contributions. Elaborate on your motives. '),
        ),
        migrations.AddField(
            model_name='player',
            name='fairness',
            field=otree.db.models.PositiveIntegerField(null=True, verbose_name="What is a 'fair' contribution in the public good?"),
        ),
        migrations.AddField(
            model_name='player',
            name='fairness_explore',
            field=otree.db.models.StringField(max_length=10000, null=True, verbose_name="Are you concerned about 'fairness' in making your investment decision? Please elaborate briefly."),
        ),
        migrations.AddField(
            model_name='player',
            name='heard_PGG',
            field=otree.db.models.BooleanField(choices=[[True, 'Yes'], [False, 'No']], verbose_name='Have you previously heard of a “public goods game”? '),
        ),
    ]
