# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2020-03-27 12:57
from __future__ import unicode_literals

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('PGGexoEN', '0020_auto_20200327_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='fairness',
            field=otree.db.models.PositiveIntegerField(null=True, verbose_name="What is a 'fair' contribution in the public good? (number)"),
        ),
        migrations.AlterField(
            model_name='player',
            name='fairness_explore',
            field=otree.db.models.LongStringField(null=True, verbose_name="Are you concerned about 'fairness' in making your contribution decision? Please elaborate briefly on your idea of 'fairness' and how important it is to you"),
        ),
        migrations.AlterField(
            model_name='player',
            name='reasons_explore',
            field=otree.db.models.LongStringField(null=True, verbose_name='Please state the reasons for your contributions. Elaborate on your motives, why did you make the decisions you did? Which of the reasons was the most important? '),
        ),
    ]
