# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2020-03-27 14:21
from __future__ import unicode_literals

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('PGGexoEN', '0021_auto_20200327_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='earnings_last_round',
            field=otree.db.models.PositiveIntegerField(null=True),
        ),
    ]
