# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2020-03-27 14:25
from __future__ import unicode_literals

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('PGGexoEN', '0022_player_earnings_last_round'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='earnings_last_round',
            field=otree.db.models.FloatField(null=True),
        ),
    ]
