# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2020-03-27 14:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PGGexoEN', '0024_auto_20200327_1528'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='earnings_last_round',
        ),
    ]
