# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2020-03-30 10:28
from __future__ import unicode_literals

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('PGGexoEN', '0026_auto_20200327_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='business',
            field=otree.db.models.BooleanField(choices=[[True, 'Yes'], [False, 'No']], verbose_name='Do you or did you study one of the following programmes: Economics and Business Administration, BSc; Erhvervsøkonomi, HA; Erhvervsøkonomi med tilvalg; Erhvervsøkonomi og erhvervsret(HA(jur.)); Economics and Business Administration, MSc (cand.merc); Marketing and Management Communication?'),
        ),
        migrations.AddField(
            model_name='player',
            name='earnings_previous_rounds',
            field=otree.db.models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='economics',
            field=otree.db.models.BooleanField(choices=[[True, 'Yes'], [False, 'No']], verbose_name='Do you or did you study one of the following programmes: Økonomi; Politik og økonomi; Matematik-økonomi?'),
        ),
    ]
