# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2020-03-30 11:04
from __future__ import unicode_literals

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('PGGexoEN', '0028_remove_player_earnings_previous_rounds'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='earnings_previous_rounds',
            field=otree.db.models.PositiveIntegerField(null=True),
        ),
    ]
