# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2020-03-16 15:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import otree.db.models
import otree_save_the_change.mixins


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('otree', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_subsession', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('group_id', otree.db.models.StringField(max_length=10000, null=True)),
                ('actual_roll_p1', otree.db.models.IntegerField(null=True)),
                ('actual_roll_p2', otree.db.models.IntegerField(null=True)),
                ('reported_roll_p1', otree.db.models.IntegerField(null=True, verbose_name='What number did you roll?')),
                ('reported_roll_p2', otree.db.models.IntegerField(null=True, verbose_name='What number did you roll?')),
                ('checked', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=True)),
                ('p1_cheat', otree.db.models.IntegerField(null=True)),
                ('p2_cheat', otree.db.models.IntegerField(null=True)),
                ('team_cheated', otree.db.models.IntegerField(null=True)),
                ('total_contribution', otree.db.models.CurrencyField(null=True)),
                ('individual_share', otree.db.models.CurrencyField(null=True)),
                ('max_amount', otree.db.models.CurrencyField(null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lcg_group', to='otree.Session')),
            ],
            options={
                'db_table': 'LCG_group',
            },
            bases=(otree_save_the_change.mixins.SaveTheChange, models.Model),
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_group', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('_payoff', otree.db.models.CurrencyField(default=0, null=True)),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('_gbat_arrived', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False)),
                ('_gbat_grouped', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False)),
                ('ingame', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=True)),
                ('age', otree.db.models.IntegerField(null=True, verbose_name='What is your age?')),
                ('gender', otree.db.models.StringField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10000, null=True, verbose_name='What is your gender?')),
                ('contribution', otree.db.models.CurrencyField(null=True)),
                ('MIq1', otree.db.models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True, verbose_name='It would make me feel good to be a person who has these characteristics.')),
                ('MIq2', otree.db.models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True, verbose_name='Being someone who has these characteristics is an important part of who I am.')),
                ('MIq3', otree.db.models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True, verbose_name='I would be ashamed to be a person who has these characteristics.')),
                ('MIq4', otree.db.models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True, verbose_name='Having these characteristics is not really important to me.')),
                ('MIq5', otree.db.models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True, verbose_name='I strongly desire to have these characteristics.')),
                ('MIq6', otree.db.models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True, verbose_name='I often wear clothes that identify me as having these characteristics.')),
                ('MIq7', otree.db.models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True, verbose_name='The types of things I do in my spare time (e.g. hobbies) clearly identify me as having these characteristics. ')),
                ('MIq8', otree.db.models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True, verbose_name='The kinds of books and magazines that I read identify me as having these characteristics.')),
                ('MIq9', otree.db.models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True, verbose_name='The fact that I have these characteristics is communicated to others by my membership in certain organizations.')),
                ('MIq10', otree.db.models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True, verbose_name='I am actively involved in activities that communicate to others that I have these characteristics.')),
                ('Dq1', otree.db.models.IntegerField(choices=[[1, '1'], [2, '2'], [3, '3'], [4, '4'], [5, '5'], [6, '6'], [7, '7']], null=True, verbose_name='Betting a day’s income at the horse races.')),
                ('Dq2', otree.db.models.IntegerField(choices=[[1, '1'], [2, '2'], [3, '3'], [4, '4'], [5, '5'], [6, '6'], [7, '7']], null=True, verbose_name='Investing 10% of your annual income in a moderate growth mutual fund.')),
                ('Dq3', otree.db.models.IntegerField(choices=[[1, '1'], [2, '2'], [3, '3'], [4, '4'], [5, '5'], [6, '6'], [7, '7']], null=True, verbose_name='Betting a day’s income at a high-stake poker game.')),
                ('Dq4', otree.db.models.IntegerField(choices=[[1, '1'], [2, '2'], [3, '3'], [4, '4'], [5, '5'], [6, '6'], [7, '7']], null=True, verbose_name='Investing 5% of your annual income in a very speculative stock.')),
                ('Dq5', otree.db.models.IntegerField(choices=[[1, '1'], [2, '2'], [3, '3'], [4, '4'], [5, '5'], [6, '6'], [7, '7']], null=True, verbose_name='Betting a day’s income on the outcome of a sporting event.')),
                ('Dq6', otree.db.models.IntegerField(choices=[[1, '1'], [2, '2'], [3, '3'], [4, '4'], [5, '5'], [6, '6'], [7, '7']], null=True, verbose_name='Investing 10% of your annual income in a new business venture.')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='LCG.Group')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lcg_player', to='otree.Participant')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lcg_player', to='otree.Session')),
            ],
            options={
                'db_table': 'LCG_player',
            },
            bases=(otree_save_the_change.mixins.SaveTheChange, models.Model),
        ),
        migrations.CreateModel(
            name='Subsession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lcg_subsession', to='otree.Session')),
            ],
            options={
                'db_table': 'LCG_subsession',
            },
            bases=(otree_save_the_change.mixins.SaveTheChange, models.Model),
        ),
        migrations.AddField(
            model_name='player',
            name='subsession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LCG.Subsession'),
        ),
        migrations.AddField(
            model_name='group',
            name='subsession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LCG.Subsession'),
        ),
    ]
