# Generated by Django 2.2.4 on 2020-03-05 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PGGRegiEN', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Player',
        ),
    ]
