# Generated by Django 2.2.4 on 2020-03-05 16:23

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('PGGRegiEN', '0003_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='rule',
            field=otree.db.models.PositiveIntegerField(choices=[[1, 'Equal sharing of the bonus'], [2, 'Equal payoff'], [3, 'No preference']], null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='rulestr',
            field=otree.db.models.PositiveIntegerField(choices=[[1, 'Seems most fair'], [2, 'Easier to understand'], [3, 'Payoffs should not be differentiated'], [4, 'Uncertain about contributions of other players'], [5, 'No preference']], null=True),
        ),
    ]
