# Generated by Django 2.2.4 on 2020-03-10 12:13

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('PGGRegiEN', '0005_auto_20200309_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='rule',
            field=otree.db.models.BooleanField(choices=[[1, 'Yes'], [2, 'No']], null=True),
        ),
    ]
