# Generated by Django 2.2.4 on 2020-03-10 12:13

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('PGGRegiEN', '0006_auto_20200310_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='rule',
            field=otree.db.models.BooleanField(choices=[[True, 'Yes'], [False, 'No']], null=True),
        ),
    ]
