# Generated by Django 2.2.4 on 2020-03-10 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PGGRegiEN', '0007_auto_20200310_1313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='rulestr',
        ),
    ]
