# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2020-03-24 14:28
from __future__ import unicode_literals

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('PGGRegiEN', '0014_auto_20200324_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='business',
            field=otree.db.models.BooleanField(choices=[[True, 'Yes'], [False, 'No']], verbose_name='Do you or did you study one of the following programmes: Economics and Business Administration, BSc; Erhvervsøkonomi, HA; Erhvervsøkonomi med tilvalg; Erhvervsøkonomi og erhvervsret(HA(jur.))?'),
        ),
        migrations.AlterField(
            model_name='player',
            name='economics',
            field=otree.db.models.BooleanField(choices=[[True, 'Yes'], [False, 'No']], verbose_name='Do you or did you study one of the following programmes: Økonomi; Politik og økonomi?'),
        ),
    ]
