# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2020-03-27 08:51
from __future__ import unicode_literals

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('PGGRegiEN', '0015_auto_20200324_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='sona_id',
            field=otree.db.models.StringField(max_length=10000, null=True, verbose_name="Input your SONA Identity Code (it's written in all emails you got from us about the study)"),
        ),
    ]
