# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2020-03-27 09:23
from __future__ import unicode_literals

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('PGGRegiEN', '0016_player_sona_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='consent',
            field=otree.db.models.BooleanField(choices=[[True, 'Yes'], [False, 'No']]),
        ),
    ]
