# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2020-03-27 10:27
from __future__ import unicode_literals

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('PGGRegiEN', '0017_player_consent'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='contribution',
            field=otree.db.models.IntegerField(null=True),
        ),
    ]
