# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2020-03-27 10:34
from __future__ import unicode_literals

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('PGGRegiEN', '0019_auto_20200327_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='semester',
            field=otree.db.models.IntegerField(null=True, verbose_name='Do you or did you study one of the following programmes: Økonomi; Politik og økonomi?'),
        ),
    ]
