# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2020-03-27 15:08
from __future__ import unicode_literals

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('PGGRegiEN', '0022_auto_20200327_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='comprehension1',
            field=otree.db.models.PositiveIntegerField(null=True, verbose_name='If you invested 30 tokens in the public good, how much of your income do you still have left (before the payment of the bonus or refund of the contributions)?'),
        ),
        migrations.AddField(
            model_name='player',
            name='comprehension2',
            field=otree.db.models.PositiveIntegerField(null=True, verbose_name='There are 5 people in your group, including you. Your income is 55 tokens. The public good threshold is 125 tokens. The group bonus for achieving the threshold is 250 tokens, equally divided between the group, e.g. 25 tokens for each player. You have contributed 25 tokens towards the public good. The contributions of the other 4 people in your group are as follows {10;25;30;20}. What is your payoff for this round?'),
        ),
        migrations.AddField(
            model_name='player',
            name='comprehension3',
            field=otree.db.models.PositiveIntegerField(null=True, verbose_name='The number of people, threshold, your income and contributions of the other people are the same as in question 2. Your contribution is different - it is 40 tokens. What is your payoff for this round?'),
        ),
    ]
