# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2020-03-30 20:07
from __future__ import unicode_literals

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('PGGRegiEN', '0026_auto_20200330_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='comprehension2',
            field=otree.db.models.PositiveIntegerField(null=True, verbose_name='There are 5 people in your group, including you. Your income is 55 tokens. The public good threshold is 125 tokens. The group bonus for achieving the threshold is 250 tokens, equally divided between the group, e.g. 50 tokens for each player. You have contributed 25 tokens towards the public good. The contributions of the other 4 people in your group are as follows {10;25;30;20}. What is your payoff for this round?'),
        ),
    ]
