# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2020-03-16 15:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0001_initial'),
        ('otree', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_name', models.CharField(max_length=1000)),
                ('app_name', models.CharField(max_length=1000)),
                ('player_id', models.PositiveIntegerField()),
                ('timestamp', models.DateTimeField()),
                ('round_number', models.PositiveIntegerField()),
                ('wait_for_images', models.BooleanField(choices=[(False, 'Before images are loaded'), (True, 'After images are loaded')], default=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otree_tools_enter_events', to='otree.Participant')),
            ],
            options={
                'get_latest_by': 'timestamp',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Exit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_name', models.CharField(max_length=1000)),
                ('app_name', models.CharField(max_length=1000)),
                ('player_id', models.PositiveIntegerField()),
                ('round_number', models.PositiveIntegerField()),
                ('timestamp', models.DateTimeField()),
                ('exit_type', models.IntegerField(choices=[(0, 'Form submitted'), (1, 'Page unloaded'), (2, 'Client disconnected')])),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('enter', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exit', to='otree_tools.Enter')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otree_tools_exit_events', to='otree.Participant')),
            ],
            options={
                'get_latest_by': 'timestamp',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FocusEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_name', models.CharField(max_length=1000)),
                ('app_name', models.CharField(max_length=1000)),
                ('player_id', models.PositiveIntegerField()),
                ('timestamp', models.DateTimeField()),
                ('round_number', models.PositiveIntegerField()),
                ('event_desc_type', models.CharField(max_length=1000)),
                ('event_num_type', models.IntegerField(choices=[(0, 'Page shown'), (4, 'Focus on'), (2, 'Focus off'), (5, 'Form submitted')])),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('entry', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='closure', to='otree_tools.FocusEvent')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otree_tools_focusevent_events', to='otree.Participant')),
            ],
            options={
                'get_latest_by': 'timestamp',
                'abstract': False,
            },
        ),
    ]
